export const ANTIKA_BRAND = {
  slug: "antika-beirut",
  branchSlug: "antika-beirut-marv-mall",
  logo: "/brands/antika/logo.svg",
  cover: "/brands/antika/cover.png",
  phone: "01101680111",
  whatsapp: "201101680111",
  reservationPhone: "01101630111",
  addressAr: "Mar.V Mall - التجمع الخامس - التسعين الشمالي",
  addressEn: "Mar.V Mall, Fifth Settlement, North 90 Street",
  instagram: "https://instagram.com/antikarestauranteg",
  facebook: "https://facebook.com/AntikaRestaurant",
};

export type AntikaItem = {
  en: string;
  ar: string;
  price: number;
  hot?: boolean;
  cold?: boolean;
  spicy?: boolean;
  vegetarian?: boolean;
  best?: boolean;
  image?: string;
};

export type AntikaCategory = {
  en: string;
  ar: string;
  image?: string;
  items: AntikaItem[];
};

export const ANTIKA_CATEGORIES: AntikaCategory[] = [
  {
    en: "Soup",
    ar: "شوربة",
    image: "/brands/antika/soup-salad.png",
    items: [
      { en: "Creamy Chicken Soup", ar: "شوربة دجاج بالكريمة", price: 260, hot: true },
      { en: "Lentil Soup", ar: "شوربة عدس", price: 190, hot: true, vegetarian: true },
      { en: "Mushroom Soup", ar: "شوربة مشروم", price: 240, hot: true, vegetarian: true },
      { en: "Lesan El Asfour", ar: "شوربة لسان عصفور", price: 180, hot: true },
    ],
  },
  {
    en: "Salads",
    ar: "سلطات",
    image: "/brands/antika/soup-salad.png",
    items: [
      { en: "Tabouleh", ar: "تبولة", price: 210, vegetarian: true },
      { en: "Fattoush", ar: "فتوش", price: 225, vegetarian: true },
      { en: "Antika Salad", ar: "سلطة أنتيكا", price: 410, best: true },
      { en: "Arabic Salad", ar: "سلطة عربية", price: 190, vegetarian: true },
      { en: "Rocca With Beetroot", ar: "روكا مع الشمندر", price: 205, vegetarian: true },
      { en: "Caesar Salad", ar: "سيزر سالاد", price: 365 },
      { en: "Vegetables Platter", ar: "طبق خضار", price: 165, vegetarian: true },
      { en: "Crab Salad", ar: "سلطة كراب", price: 450 },
    ],
  },
  {
    en: "Raw",
    ar: "النية",
    items: [
      { en: "Lebanese Kibbeh", ar: "كبة لبنانية", price: 450 },
      { en: "Habra Nayyeh", ar: "هبرة نية", price: 460 },
      { en: "Frakeh Orfali", ar: "فركة أورفلي", price: 500, spicy: true },
    ],
  },
  {
    en: "Cold Mazza",
    ar: "مازة باردة",
    items: [
      { en: "Hummus", ar: "حمص", price: 145, vegetarian: true },
      { en: "Motabbal", ar: "متبل", price: 140, vegetarian: true },
      { en: "Al Raheb", ar: "الراهب", price: 205, vegetarian: true },
      { en: "Vine Leaves", ar: "ورق عنب", price: 207, vegetarian: true },
      { en: "Muhammara", ar: "محمرة", price: 215, vegetarian: true, spicy: true },
      { en: "Loubia", ar: "لوبيا بالزيت", price: 180, vegetarian: true },
      { en: "Mosaka", ar: "مسقعة بالباذنجان", price: 175, vegetarian: true },
      { en: "Labneh Beiruti", ar: "لبنة بيروتي", price: 180, vegetarian: true },
      { en: "Marinated Labneh", ar: "لبنة بالخلطة", price: 165, vegetarian: true },
      { en: "Cheese & Za'atar", ar: "جبنة وزعتر", price: 145, vegetarian: true },
      { en: "Shanklish", ar: "شنكليش", price: 120, vegetarian: true },
      { en: "Kabis Platter", ar: "طبق كبيس", price: 92, vegetarian: true },
      { en: "Beirut Hummus", ar: "حمص بيروتي", price: 230, vegetarian: true },
      { en: "Mix Hummus", ar: "حمص ميكس", price: 310, vegetarian: true },
    ],
  },
  {
    en: "Hot Mazza",
    ar: "مازة ساخنة",
    items: [
      { en: "Makanek", ar: "مقانق", price: 345, hot: true },
      { en: "Sausage", ar: "سجق", price: 355, hot: true, spicy: true },
      { en: "Chicken Liver", ar: "سودة دجاج", price: 304, hot: true },
      { en: "Chilli Potatoes", ar: "بطاطا حارة", price: 195, hot: true, spicy: true, vegetarian: true },
      { en: "French Fries", ar: "بطاطا مقلية", price: 155, hot: true, vegetarian: true },
      { en: "Hummus With Beef", ar: "حمص باللحمة", price: 485, hot: true },
      { en: "Hummus Shawarma", ar: "حمص بالشاورما", price: 495, hot: true },
      { en: "Ras Asfour", ar: "لحمة رأس عصفور", price: 485, hot: true },
      { en: "Kibbeh", ar: "كبة مقلية", price: 240, hot: true },
      { en: "Beef Sambousk", ar: "سمبوسك لحمة", price: 225, hot: true },
      { en: "Cheese Chips", ar: "رقاقات بالجبنة", price: 215, hot: true, vegetarian: true },
      { en: "Mix Moajanat Platter", ar: "طبق معجنات مشكل", price: 365, hot: true },
      { en: "Halloumi With Basil", ar: "حلوم بالريحان", price: 305, hot: true, vegetarian: true },
      { en: "Halloumi With Fig", ar: "حلوم مع التين", price: 309, hot: true, vegetarian: true },
      { en: "Chicken Wings", ar: "جوانح الدجاج", price: 310, hot: true },
      { en: "Wings", ar: "جوانح", price: 410, hot: true },
      { en: "Tawook", ar: "طاووق", price: 480, hot: true },
      { en: "Cheese Burek", ar: "برك بالجبنة", price: 320, hot: true, vegetarian: true },
      { en: "Mixed Chips", ar: "ميكس رقاقات", price: 430, hot: true },
    ],
  },
  {
    en: "Fattah",
    ar: "فتة",
    image: "/brands/antika/grills.png",
    items: [
      { en: "Eggplant Fatteh", ar: "فتة باذنجان", price: 235, hot: true, vegetarian: true },
      { en: "Hummus Fatteh", ar: "فتة حمص", price: 205, hot: true, vegetarian: true },
      { en: "Chicken Shawarma Fatteh", ar: "فتة شاورما دجاج", price: 325, hot: true },
      { en: "Beef Shawarma Fatteh", ar: "فتة شاورما لحمة", price: 345, hot: true },
    ],
  },
  {
    en: "Grills",
    ar: "مشاوي",
    image: "/brands/antika/grills.png",
    items: [
      { en: "Mix Grill", ar: "مشوي مشكل", price: 880, hot: true, best: true },
      { en: "Shaqaf Meat", ar: "لحمة شقف", price: 770, hot: true },
      { en: "Chicken Grill", ar: "شيش طاووق", price: 527, hot: true },
      { en: "Kafta", ar: "كفتة", price: 502, hot: true },
      { en: "Khashkhash Kabab", ar: "كباب خشخاش", price: 625, hot: true, spicy: true },
      { en: "Orfali Kabab", ar: "كباب أورفلي", price: 630, hot: true, spicy: true },
      { en: "Kabab with Eggplant", ar: "كباب مع الباذنجان", price: 655, hot: true },
      { en: "Ribs", ar: "ريش", price: 1080, hot: true },
      { en: "Grilled Wings", ar: "أجنحة مشوية", price: 450, hot: true },
      { en: "Arayes Kafta", ar: "عرايس كفتة", price: 447, hot: true },
      { en: "Boneless Chicken", ar: "دجاج مسحب", price: 620, hot: true },
      { en: "Kafta With Tahini", ar: "كفتة مع الطحينة", price: 637, hot: true },
      { en: "Grilled Vegetables", ar: "خضروات مشوية", price: 197, hot: true, vegetarian: true },
      { en: "Provencal Tawouk", ar: "طاووق بروفنسال", price: 580, hot: true },
      { en: "Kebab Antika", ar: "كباب أنتيكا", price: 720, hot: true, best: true },
      { en: "Steak Roll", ar: "رول ستيك", price: 850, hot: true },
    ],
  },
  {
    en: "Main Dishes",
    ar: "الأطباق الرئيسية",
    items: [
      { en: "Steak Fillet", ar: "ستيك فيليه", price: 790, hot: true },
      { en: "Grilled Chicken", ar: "دجاج مشوي", price: 625, hot: true },
      { en: "Cordon Bleu", ar: "كوردون بلو", price: 600, hot: true },
      { en: "Beef Fajita", ar: "فاهيتا لحم", price: 530, hot: true },
      { en: "Chicken Escalope", ar: "اسكالوب دجاج", price: 520, hot: true },
      { en: "Chicken Shawarma", ar: "شاورما دجاج", price: 505, hot: true },
      { en: "Beef Shawarma", ar: "شاورما لحمة", price: 565, hot: true },
    ],
  },
  {
    en: "Pasta",
    ar: "باستا",
    items: [
      { en: "Chicken Alfredo", ar: "ألفريدو دجاج", price: 325, hot: true },
      { en: "Bolognese Pasta", ar: "باستا بولونيز", price: 300, hot: true },
      { en: "Chicken Pesto", ar: "بيستو دجاج", price: 242, hot: true },
      { en: "Sausage Pasta", ar: "باستا بالسجق", price: 335, hot: true, spicy: true },
    ],
  },
  {
    en: "Sandwiches",
    ar: "سندوتشات",
    items: [
      { en: "Chicken Crispy", ar: "كريسبي دجاج", price: 335, hot: true },
      { en: "Fajita Chicken", ar: "فاهيتا دجاج", price: 347, hot: true },
      { en: "Classic Burger", ar: "برجر كلاسيك", price: 352, hot: true },
      { en: "Mushroom Burger", ar: "برجر مشروم", price: 362, hot: true },
      { en: "Cheese Burger", ar: "برجر بالجبنة", price: 372, hot: true },
      { en: "Kafta", ar: "كفتة", price: 245, hot: true },
      { en: "Chicken Grill", ar: "شيش طاووق", price: 295, hot: true },
      { en: "Grilled Meat", ar: "لحمة مشوية", price: 380, hot: true },
    ],
  },
  {
    en: "Pizza",
    ar: "بيتزا",
    items: [
      { en: "Pepperoni Pizza", ar: "بيتزا بيبروني", price: 320, hot: true },
      { en: "Mushroom Pizza", ar: "بيتزا مشروم", price: 395, hot: true, vegetarian: true },
      { en: "BBQ Chicken Pizza", ar: "بيتزا دجاج باربيكيو", price: 355, hot: true },
    ],
  },
  {
    en: "Manakish",
    ar: "مناقيش",
    items: [
      { en: "Cheese", ar: "جبنة", price: 218, hot: true, vegetarian: true },
      { en: "Cheese With Za'atar", ar: "جبنة مع زعتر", price: 225, hot: true, vegetarian: true },
      { en: "Keshek", ar: "كشك", price: 154, hot: true, vegetarian: true },
      { en: "Za'atar", ar: "زعتر", price: 170, hot: true, vegetarian: true },
      { en: "Za'atar & Labneh", ar: "زعتر ولبنة", price: 178, hot: true, vegetarian: true },
      { en: "Lahm B Aajin", ar: "لحم بعجين", price: 280, hot: true },
      { en: "Lahmi With Cheese", ar: "لحمة وجبنة", price: 325, hot: true },
      { en: "Cheese And Sausage", ar: "جبنة وسجق", price: 305, hot: true },
      { en: "Spinach", ar: "سبانخ", price: 154, hot: true, vegetarian: true },
      { en: "Labneh", ar: "لبنة", price: 148, hot: true, vegetarian: true },
      { en: "Halloumi Cheese Safeeha", ar: "صفيحة حلوم", price: 183, hot: true, vegetarian: true },
      { en: "Beef Safeeha", ar: "صفيحة لحمة", price: 206, hot: true },
      { en: "Spinach Safeeha", ar: "صفيحة سبانخ", price: 162, hot: true, vegetarian: true },
      { en: "Safeeha Mix", ar: "صفيح مشكل", price: 250, hot: true },
      { en: "Jibneh W Muhammara", ar: "جبنة ومحمرة", price: 188, hot: true, vegetarian: true, spicy: true },
      { en: "Chicken Shawarma Pie", ar: "فطيرة شاورما فراخ", price: 350, hot: true },
      { en: "Beef Shawarma Pie", ar: "فطيرة شاورما لحمة", price: 380, hot: true },
      { en: "Baalbaki Safeeha", ar: "صفيحة بعلبكية", price: 335, hot: true },
      { en: "Safaieh Extra", ar: "صفايح إكسترا", price: 380, hot: true },
    ],
  },
  {
    en: "Extras",
    ar: "إضافات",
    items: [
      { en: "White Rice", ar: "أرز أبيض", price: 74, hot: true, vegetarian: true },
      { en: "Oriental Rice", ar: "أرز بالخلطة", price: 112, hot: true },
      { en: "Garlic", ar: "تومية", price: 46, vegetarian: true },
      { en: "Tahina", ar: "طحينة", price: 63, vegetarian: true },
      { en: "Sauteed Vegetables", ar: "خضار سوتيه", price: 74, hot: true, vegetarian: true },
      { en: "Cheese", ar: "جبنة", price: 51, vegetarian: true },
      { en: "Mushrooms", ar: "مشروم", price: 51, vegetarian: true },
      { en: "Mashed Potato", ar: "بطاطا مهروسة", price: 103, hot: true, vegetarian: true },
      { en: "Welcome", ar: "ضيافة", price: 103 },
    ],
  },
  {
    en: "Dessert",
    ar: "حلويات",
    items: [
      { en: "Gazal Beirut", ar: "غزل بيروت", price: 277 },
      { en: "Em Ali", ar: "أم علي", price: 205 },
      { en: "Mohlabya", ar: "مهلبية", price: 205 },
      { en: "Rez B Halib", ar: "أرز بالحليب", price: 205 },
      { en: "Nabolsia", ar: "كنافة نابلسية", price: 324 },
      { en: "Baklava", ar: "بقلاوة", price: 300 },
      { en: "Halawet El Jeben", ar: "حلاوة الجبن", price: 350 },
      { en: "Molten Cake", ar: "مولتن كيك", price: 276 },
      { en: "Brownies", ar: "براونيز", price: 216 },
      { en: "Crepe Nutella", ar: "كريب نوتيلا", price: 247 },
      { en: "Fruit Plate (L)", ar: "طبق فواكه كبير", price: 450, cold: true },
      { en: "Nuts", ar: "مكسرات", price: 450 },
      { en: "Tajin Potato", ar: "طاجن بطاطا", price: 256, hot: true },
      { en: "Tajin Crepe", ar: "طاجن كريب", price: 305, hot: true },
      { en: "Lebanese Desserts", ar: "حلويات لبنانية", price: 372 },
    ],
  },
  {
    en: "Fresh Juice",
    ar: "عصائر طازجة",
    image: "/brands/antika/fresh-juice.png",
    items: [
      { en: "Mango", ar: "مانجو", price: 188, cold: true },
      { en: "Strawberry", ar: "فراولة", price: 188, cold: true },
      { en: "Orange", ar: "برتقال", price: 182, cold: true },
      { en: "Lemon Mint", ar: "ليمون بالنعناع", price: 165, cold: true },
      { en: "Guava", ar: "جوافة", price: 188, cold: true },
      { en: "Lemonade", ar: "ليمون", price: 165, cold: true },
      { en: "Kiwi", ar: "كيوي", price: 188, cold: true },
      { en: "Peach", ar: "خوخ", price: 188, cold: true },
      { en: "Watermelon", ar: "بطيخ", price: 188, cold: true },
      { en: "Pineapple", ar: "أناناس", price: 194, cold: true },
      { en: "Cantaloupe", ar: "كنتالوب", price: 194, cold: true },
      { en: "Banana With Milk", ar: "موز بالحليب", price: 194, cold: true },
      { en: "Seasonal Fruits", ar: "فواكه موسمية", price: 177, cold: true },
      { en: "Pomegranate", ar: "رمان", price: 177, cold: true },
    ],
  },
  {
    en: "Cocktails",
    ar: "كوكتيلات",
    image: "/brands/antika/fresh-juice.png",
    items: [
      { en: "Avocado Cocktail", ar: "كوكتيل أفوكادو", price: 214, cold: true },
      { en: "Antika Cocktail", ar: "كوكتيل أنتيكا", price: 237, cold: true, best: true },
      { en: "Guava Mint", ar: "جوافة بالنعناع", price: 182, cold: true },
      { en: "Red Kiwi", ar: "كيوي أحمر", price: 182, cold: true },
      { en: "Pina Colada", ar: "بينا كولادا", price: 203, cold: true },
      { en: "Kiwi Pineapple", ar: "كيوي أناناس", price: 209, cold: true },
      { en: "Banana Orange", ar: "موز بالبرتقال", price: 166, cold: true },
      { en: "Pineapple Peach", ar: "أناناس بالخوخ", price: 166, cold: true },
      { en: "Orange Pineapple", ar: "برتقال أناناس", price: 180, cold: true },
    ],
  },
  {
    en: "Milkshake",
    ar: "ميلك شيك",
    image: "/brands/antika/fresh-juice.png",
    items: [
      { en: "Mix Berry", ar: "ميكس بيري", price: 199, cold: true },
      { en: "Lotus Milkshake", ar: "ميلك شيك لوتس", price: 223, cold: true },
      { en: "Oreo Milkshake", ar: "ميلك شيك أوريو", price: 228, cold: true },
      { en: "Chocolate Milkshake", ar: "ميلك شيك شوكولاتة", price: 216, cold: true },
      { en: "Snickers Milkshake", ar: "ميلك شيك سنيكرز", price: 228, cold: true },
      { en: "Nuts Milkshake", ar: "ميلك شيك مكسرات", price: 239, cold: true },
    ],
  },
  {
    en: "Mojito & Ice Tea",
    ar: "موهيتو وشاي مثلج",
    items: [
      { en: "Strawberry Mojito", ar: "موهيتو فراولة", price: 192, cold: true },
      { en: "Blueberry Mojito", ar: "موهيتو توت أزرق", price: 198, cold: true },
      { en: "Classic Mojito", ar: "موهيتو كلاسيك", price: 177, cold: true },
      { en: "Passion Fruit Mojito", ar: "موهيتو باشن فروت", price: 195, cold: true },
      { en: "Pink Lemonade", ar: "ليمون وردي", price: 169, cold: true },
      { en: "Ice Tea Peach", ar: "شاي مثلج خوخ", price: 170, cold: true },
      { en: "Ice Tea Peach Lemon", ar: "شاي مثلج خوخ ليمون", price: 176, cold: true },
      { en: "Ice Tea Berry", ar: "شاي مثلج بيري", price: 170, cold: true },
    ],
  },
  {
    en: "Frappe",
    ar: "فرابيه",
    items: [
      { en: "Vanilla Frappe", ar: "فرابيه فانيليا", price: 212, cold: true },
      { en: "Frappuccino Caramel", ar: "فرابتشينو كراميل", price: 201, cold: true },
      { en: "Mocha Frappe", ar: "فرابيه موكا", price: 206, cold: true },
      { en: "Frappe Chocolate", ar: "فرابيه شوكولاتة", price: 195, cold: true },
      { en: "Fruits Frappe", ar: "فرابيه فواكه", price: 199, cold: true },
      { en: "Ice Chocolate Dark", ar: "شوكولاتة مثلجة داكنة", price: 191, cold: true },
      { en: "Ice Chocolate White", ar: "شوكولاتة مثلجة بيضاء", price: 200, cold: true },
    ],
  },
  {
    en: "Soft Drinks",
    ar: "مشروبات غازية",
    items: [
      { en: "Small Water", ar: "مياه صغيرة", price: 33, cold: true },
      { en: "Large Water", ar: "مياه كبيرة", price: 39, cold: true },
      { en: "Perrier", ar: "بيرييه", price: 85, cold: true },
      { en: "Pepsi", ar: "بيبسي", price: 52, cold: true },
      { en: "Seven-Up", ar: "سفن أب", price: 52, cold: true },
      { en: "Diet Seven-Up", ar: "سفن أب دايت", price: 52, cold: true },
      { en: "Red Bull", ar: "ريد بول", price: 140, cold: true },
      { en: "Schweppes", ar: "شويبس", price: 68, cold: true },
      { en: "Fayrouz", ar: "فيروز", price: 63, cold: true },
    ],
  },
  {
    en: "Hot Drinks",
    ar: "المشروبات الساخنة",
    image: "/brands/antika/hot-drinks.png",
    items: [
      { en: "Espresso", ar: "إسبريسو", price: 95, hot: true },
      { en: "Double Espresso", ar: "دوبل إسبريسو", price: 110, hot: true },
      { en: "Macchiato", ar: "ماكياتو", price: 115, hot: true },
      { en: "Cafe Latte", ar: "كافيه لاتيه", price: 125, hot: true },
      { en: "Cappuccino", ar: "كابتشينو", price: 135, hot: true },
      { en: "Flat White", ar: "فلات وايت", price: 140, hot: true },
      { en: "Americano", ar: "أمريكانو", price: 120, hot: true },
      { en: "Cafe Mocha", ar: "كافيه موكا", price: 135, hot: true },
      { en: "Hot Chocolate", ar: "هوت شوكليت", price: 170, hot: true },
      { en: "Hot Nutella", ar: "نوتيلا ساخنة", price: 210, hot: true },
      { en: "Turkish Coffee", ar: "قهوة تركية", price: 140, hot: true },
      { en: "French Coffee", ar: "قهوة فرنسية", price: 170, hot: true },
      { en: "Hazelnut Coffee", ar: "قهوة بندق", price: 175, hot: true },
      { en: "Tea", ar: "شاي", price: 90, hot: true },
      { en: "Flavored Tea", ar: "شاي نكهات", price: 97, hot: true },
      { en: "Hot Cider", ar: "هوت سيدر", price: 130, hot: true },
      { en: "Herbs Tea", ar: "شاي أعشاب", price: 145, hot: true },
      { en: "Cafe Blanc", ar: "قهوة بيضاء", price: 130, hot: true },
      { en: "Nescafe", ar: "نسكافيه", price: 120, hot: true },
      { en: "Sahlab", ar: "سحلب", price: 125, hot: true },
      { en: "Add Flavor", ar: "إضافة نكهة", price: 56 },
      { en: "Teapot", ar: "براد شاي", price: 210, hot: true },
    ],
  },
  {
    en: "Shisha",
    ar: "شيشة",
    items: [
      { en: "Lebanese Ajami", ar: "أعجمي لبناني", price: 560 },
      { en: "Shisha Antika", ar: "شيشة أنتيكا", price: 250, best: true },
      { en: "Shisha Beirut", ar: "شيشة بيروت", price: 350 },
      { en: "Shisha Baladi", ar: "شيشة بلدي", price: 120 },
    ],
  },
  {
    en: "Breakfast",
    ar: "الفطار",
    items: [
      { en: "Labneh & Za'atar", ar: "لبنة وزعتر", price: 160, vegetarian: true },
      { en: "Hummus & Foul", ar: "حمص وفول", price: 170, vegetarian: true },
      { en: "Eggs With Kawerma", ar: "بيض بقورما", price: 280, hot: true },
      { en: "Omelet With Vegetables", ar: "أومليت بالخضار", price: 170, hot: true, vegetarian: true },
      { en: "Eggs Scrambled", ar: "بيض مخفوق", price: 160, hot: true, vegetarian: true },
      { en: "Falafel", ar: "فلافل", price: 176, hot: true, vegetarian: true },
      { en: "Feta Cheese with Za'atar", ar: "فيتا بالزعتر", price: 148, vegetarian: true },
      { en: "Feta Cheese with Vegetables", ar: "فيتا بالخضار", price: 148, vegetarian: true },
      { en: "Mix Cheese", ar: "ميكس جبن", price: 520, vegetarian: true },
      { en: "Butter and Jam", ar: "زبدة ومربى", price: 210, vegetarian: true },
    ],
  },
  {
    en: "Daily Dishes",
    ar: "الأطباق اليومية",
    items: [
      { en: "Kibbeh With Milk", ar: "كبة باللبن", price: 345, hot: true },
      { en: "Kafta Bil Sanieh", ar: "كفتة بالصينية", price: 430, hot: true },
      { en: "Cutlet With Stuffed", ar: "كستلاتة مع محشي", price: 640, hot: true },
      { en: "Kibbeh Bil Sanieh", ar: "كبة بالصينية", price: 480, hot: true },
      { en: "Stuffed Lamb", ar: "خروف محشي", price: 520, hot: true },
      { en: "Chuchvara", ar: "شيش برك", price: 265, hot: true },
      { en: "Basha Dawood", ar: "داوود باشا", price: 280, hot: true },
      { en: "Rice White", ar: "أرز أبيض", price: 90, hot: true },
      { en: "Mulukhiyah Lebanese", ar: "ملوخية لبنانية", price: 350, hot: true },
      { en: "Rice with Chicken", ar: "أرز بالدجاج", price: 320, hot: true },
      { en: "Chicken Kabsa", ar: "كبسة بالدجاج", price: 420, hot: true },
      { en: "Chicken Mandi", ar: "مندي بالدجاج", price: 445, hot: true },
      { en: "Chicken Biryani", ar: "برياني بالدجاج", price: 465, hot: true },
      { en: "Freekeh with Meat", ar: "فريكة باللحمة", price: 570, hot: true },
      { en: "Freekeh with Chicken", ar: "فريكة بالدجاج", price: 510, hot: true },
      { en: "Sayadieh Fish", ar: "صيادية سمك", price: 610, hot: true },
      { en: "Ouzi with Meat", ar: "أوزي باللحمة", price: 670, hot: true },
      { en: "Chicken Tagine", ar: "طاجن فراخ", price: 650, hot: true },
    ],
  },
];
