export const SOUL_BRAND = {
  slug: "soul-restaurant",
  branchSlug: "soul-cloud5-sheikh-zayed",
  logo: "/brands/soul/logo.svg",
  cover: "/brands/soul/cover.png",
  phone: "01044223232",
  whatsapp: "201044223232",
  reservationPhone: "01044223232",
  addressAr: "Cloud 5 Mall - الشيخ زايد",
  addressEn: "Cloud 5 Mall, Sheikh Zayed",
  instagram: "https://instagram.com/soulrestauranteg",
  facebook: "https://facebook.com/soulrestauranteg",
};

export type SoulItem = {
  en: string;
  ar: string;
  price: number;
  image?: string;
  hot?: boolean;
  cold?: boolean;
  spicy?: boolean;
  vegetarian?: boolean;
  best?: boolean;
};

export type SoulCategory = {
  en: string;
  ar: string;
  image?: string;
  items: SoulItem[];
};

export const SOUL_DRINK_CATEGORIES = ["Milkshakes","The Ice Section","The Cocktail Collection","Ice Teas","Frappé","Smoothie","Cocktails","Juices","Hot Beverages"] as const;

export const SOUL_CATEGORIES: SoulCategory[] = [
  {
    en: "Tortilla Omelets",
    ar: "أومليت التورتilla",
    items: [
      { en: "Eastern Tortilla", ar: "تورتilla شرقي", price: 250 },
      { en: "Turkey Parm", ar: "تركي بارم", price: 260 },
      { en: "Sausage Veges", ar: "سجق وخضار", price: 290 },
    ],
  },
  {
    en: "Shakshuka Style",
    ar: "شكشوكة",
    items: [
      { en: "Club Shakshuka", ar: "شكشوكة كلوب", price: 295, best: true },
      { en: "Green Feta Shakshuka", ar: "شكشوكة فيتا خضراء", price: 280, vegetarian: true },
      { en: "Harissa Heat", ar: "شكشوكة هرissa", price: 250, spicy: true },
    ],
  },
  {
    en: "Tablia Sharing",
    ar: "تبلي للمشاركة",
    items: [
      { en: "Mosaique Tablia", ar: "تبلي موزاييك", price: 380, best: true },
      { en: "Fornah Tablia", ar: "تبلي فطائر", price: 355 },
      { en: "Meshaltet Tablia", ar: "تبلي فطير مشلتت", price: 340 },
    ],
  },
  {
    en: "Loaf Love",
    ar: "لفات الحب",
    items: [
      { en: "Hummus Haloumi", ar: "حمص حلوم", price: 250, vegetarian: true },
      { en: "Cheese Tomato", ar: "جبن وطماطم", price: 210, vegetarian: true },
      { en: "Smoky Salmon", ar: "سلمون مدخن", price: 290 },
      { en: "Tenderloin Chimichurri", ar: "تندرloin chimichurri", price: 310, best: true },
      { en: "Shrimp Basil", ar: "جمبري بريز", price: 320 },
    ],
  },
  {
    en: "Healthy Bowls",
    ar: "بوولز صحية",
    items: [
      { en: "Fat Burner", ar: "فات بيرنر", price: 185, vegetarian: true },
      { en: "Banana Powder", ar: "موز وبروتين", price: 165, vegetarian: true },
    ],
  },
  {
    en: "Chia Pudding",
    ar: "بودينغ الشيا",
    items: [
      { en: "Vanilla Berry Bliss", ar: "فانيليا وتوت", price: 170, vegetarian: true },
      { en: "Coconut Mango Paradise", ar: "مانجو وجوز هند", price: 175, vegetarian: true },
    ],
  },
  {
    en: "Overnight Oats",
    ar: "شوفان ليلي",
    items: [
      { en: "Banana Date Nut Oats", ar: "شوفان موز وتمر", price: 150, vegetarian: true },
      { en: "Protein Madness", ar: "بروتين مادنس", price: 170 },
    ],
  },
  {
    en: "The Croissant Bar",
    ar: "بار الكرواسون",
    items: [
      { en: "Butter Croissant", ar: "كرواسون زبدة", price: 115, vegetarian: true },
      { en: "Pistachio Cream Croissant", ar: "كرواسون فستق", price: 195, vegetarian: true },
      { en: "Cheesecake Croissant", ar: "كرواسون تشيز كيك", price: 165, vegetarian: true },
      { en: "Almond Croissant", ar: "كرواسون لوز", price: 165, vegetarian: true },
      { en: "Chocolate Hazelnut", ar: "شوكولاتة بندق", price: 160, vegetarian: true },
      { en: "Pain au Chocolat", ar: "بان أو شوكولاتة", price: 145, vegetarian: true },
      { en: "Pain au Swiss", ar: "بان أو سويس", price: 145, vegetarian: true },
      { en: "Pain au Raisin", ar: "بان أو زبيب", price: 165, vegetarian: true },
    ],
  },
  {
    en: "Stack Attack",
    ar: "ساندوتشات مكدّسة",
    items: [
      { en: "Chicken 2 Way", ar: "دجاج طريقتين", price: 270 },
      { en: "Roast Beef", ar: "روست بيف", price: 290 },
      { en: "Salmon Smoky", ar: "سلمون مدخن", price: 330 },
      { en: "Pesto Turkey", ar: "تركي بيستو", price: 280 },
      { en: "Tuna Crunch", ar: "تونة كرانش", price: 275 },
    ],
  },
  {
    en: "Cozy Sips",
    ar: "شوربات",
    items: [
      { en: "Thai Coconut Chicken Soup", ar: "شوربة تايلاندية", price: 180, hot: true },
      { en: "Tomato Pepper Soup", ar: "شوربة طماطم وفلفل", price: 160, hot: true, vegetarian: true },
      { en: "Hungarian Mushroom Soup", ar: "شوربة مشروم", price: 170, hot: true, vegetarian: true },
      { en: "Hearty Lentil and Bacon Soup", ar: "شوربة عدس", price: 155, hot: true },
    ],
  },
  {
    en: "Green Goodness",
    ar: "سلطات خضراء",
    items: [
      { en: "Peanut Crunch Salad", ar: "سلطة فول سوداني", price: 280, vegetarian: true },
      { en: "Halloumi Greek", ar: "سلطة حلوم يوناني", price: 290, vegetarian: true },
      { en: "Jala Shrimp", ar: "سلطة جمبري", price: 330 },
      { en: "Thai Beef", ar: "سلطة لحم تايلاندية", price: 310 },
      { en: "Rainbow Quinoa Salad", ar: "سلطة كinoa", price: 320, vegetarian: true },
      { en: "Fattoush Garden Bowl", ar: "فتوش", price: 260, vegetarian: true },
    ],
  },
  {
    en: "Casual Dishes",
    ar: "أطباق خفيفة",
    items: [
      { en: "Zesty Fried Shrimp", ar: "جمبري مقلي", price: 260 },
      { en: "Chicken Mac n Cheese", ar: "ماك أند تشيز دجاج", price: 240 },
      { en: "Golden Chicken", ar: "دجاج ذهبي", price: 230 },
      { en: "Buffalo Wings", ar: "بافلو وينجز", price: 220, spicy: true },
      { en: "Truffle Parmesan Fries", ar: "بطاطس ترافل", price: 240, vegetarian: true },
      { en: "Sausage Wonton", ar: "سجق wonton", price: 335 },
      { en: "Beef Truffle Croquettes", ar: "كروكيت لحم", price: 260 },
    ],
  },
  {
    en: "All In Bun",
    ar: "برجر",
    items: [
      { en: "Original Smash Burger", ar: "برجر أوريجينال", price: 310, best: true },
      { en: "Truffle Beef Burger", ar: "برجر ترافل", price: 335 },
      { en: "Fried Hot Chicken", ar: "دجاج حار", price: 280, spicy: true },
      { en: "Golden Chicken Burger", ar: "برجر دجاج", price: 275 },
    ],
  },
  {
    en: "Pasta Parade",
    ar: "باستا",
    items: [
      { en: "Buffalo Golden Chicken", ar: "باستا بافلو دجاج", price: 310 },
      { en: "Chicken Gremolata", ar: "باستا جريمولاتا", price: 295 },
      { en: "Lemon Crema Pesto", ar: "باستا بيستو", price: 250, vegetarian: true },
      { en: "Spaghetti Marinara", ar: "سباغيتي مارينارا", price: 250, vegetarian: true },
      { en: "Bolognese Ragout", ar: "بولونيز", price: 290 },
      { en: "Tuscan Creamy Shrimp", ar: "باستا جمبري", price: 355 },
      { en: "Duxelle Truffle Beef", ar: "باستا لحم ترافل", price: 385 },
    ],
  },
  {
    en: "The Big Bite",
    ar: "الأطباق الرئيسية",
    items: [
      { en: "Beef Chimichurri", ar: "لحم chimichurri", price: 540, best: true },
      { en: "Smoky Sichuan Beef", ar: "لحم sichuan", price: 530, spicy: true },
      { en: "Osso Buco alla Milanese", ar: "أوسو بuco", price: 590 },
      { en: "Veal Scaloppine al Limone", ar: "عجل ليمون", price: 499 },
      { en: "Mac and Chicken", ar: "ماك أند تشيز دجاج", price: 410 },
      { en: "Stuffed Chicken", ar: "دجاج محشي", price: 390 },
      { en: "Cordon Boom", ar: "كوردون بوم", price: 395 },
      { en: "Chicken Kebab", ar: "كباب دجاج", price: 375 },
      { en: "Persian Chicken", ar: "دجاج فارسي", price: 390 },
      { en: "Salmon Middle East", ar: "سلمون شرق أوسطي", price: 650 },
      { en: "Gremolata Fried Shrimp", ar: "جمبري gremolata", price: 590 },
    ],
  },
  {
    en: "Pizza Spot",
    ar: "بيتزا",
    items: [
      { en: "Regina Margherita", ar: "مارغريتا", price: 290, vegetarian: true },
      { en: "New York Margarita", ar: "نيويورك مارغريتا", price: 310, vegetarian: true },
      { en: "Diavola Piccante", ar: "ديavola", price: 340, spicy: true },
      { en: "Capricciosa", ar: "كابريتشiosa", price: 315 },
      { en: "Tonno Cipolla", ar: "تونة وبصل", price: 310 },
      { en: "Quattro Formaggi", ar: "أربعة أجبان", price: 340, vegetarian: true },
      { en: "Tartufo Napoletano", ar: "ترافل نابولي", price: 355, vegetarian: true },
      { en: "Salsiccia & Friarielli", ar: "سجق وبروكلي", price: 349 },
      { en: "Pesto e Pomodorin", ar: "بيستو وطماطم", price: 320, vegetarian: true },
      { en: "Bresaola Eleganza", ar: "بresaola", price: 360 },
      { en: "Fiamma Rossa", ar: "فiamma rossa", price: 345, spicy: true },
      { en: "Frutti di Mare", ar: "فruitti di mare", price: 380 },
      { en: "Gamberi e Limone", ar: "جمبري وليمون", price: 370 },
    ],
  },
  {
    en: "Milkshakes",
    ar: "ميلك شيك",
    items: [
      { en: "Vanilla Milkshake", ar: "فانيليا", price: 180, cold: true },
      { en: "Milkshake Brownies", ar: "براونيز", price: 230, cold: true },
      { en: "Lotus Milkshake", ar: "لوتس", price: 205, cold: true },
      { en: "Strawberry Milkshake", ar: "فراولة", price: 180, cold: true },
      { en: "Vanilla Banana Milkshake", ar: "موز فانيليا", price: 190, cold: true },
      { en: "Chocolate Milkshake", ar: "شوكولاتة", price: 190, cold: true },
      { en: "Mixed Berry Milkshake", ar: "توت مشكل", price: 199, cold: true },
      { en: "Oreo Milkshake", ar: "أوريو", price: 210, cold: true },
      { en: "Kinder Milkshake", ar: "كinder", price: 185, cold: true },
    ],
  },
  {
    en: "The Ice Section",
    ar: "قهوة باردة",
    items: [
      { en: "Ice Spanish Latte", ar: "سبانish latte", price: 150, cold: true },
      { en: "Peanut Butter Ice Latte", ar: "latte زبدة فول", price: 180, cold: true },
      { en: "Iced Latte", ar: "latte بارد", price: 130, cold: true },
      { en: "Iced Mocha", ar: "mocha بارد", price: 140, cold: true },
      { en: "Iced Latte Salted Caramel", ar: "latte كaramel", price: 155, cold: true },
      { en: "Kinder Iced Latte", ar: "kinder latte", price: 160, cold: true },
    ],
  },
  {
    en: "The Cocktail Collection",
    ar: "كوكتيلات",
    items: [
      { en: "Smoking Apple", ar: "تفاح مدخن", price: 145, cold: true },
      { en: "Black Star", ar: "بلاك ستار", price: 185, cold: true },
      { en: "Lavender Lemon", ar: "لافندر ليمون", price: 175, cold: true },
      { en: "Strawberry Blue Soda", ar: "صودا فراولة", price: 160, cold: true },
      { en: "Classic Mojito", ar: "mojito كلاسيك", price: 155, cold: true },
      { en: "Mojito Soul", ar: "mojito soul", price: 195, cold: true, best: true },
      { en: "Red Bull Mojito", ar: "red bull mojito", price: 220, cold: true },
      { en: "Black Mojito", ar: "mojito أسود", price: 165, cold: true },
    ],
  },
  {
    en: "Ice Teas",
    ar: "شاي مثلّج",
    items: [
      { en: "Ice Tea Apple", ar: "شاي تفاح", price: 125, cold: true },
      { en: "Ice Tea Peach", ar: "شاي خوخ", price: 125, cold: true },
      { en: "Ice Tea Soul", ar: "شاي soul", price: 145, cold: true },
      { en: "Ice Tea Passion Fruit", ar: "شاي passion", price: 145, cold: true },
      { en: "Strawberry Iced Tea", ar: "شاي فراولة", price: 140, cold: true },
    ],
  },
  {
    en: "Frappé",
    ar: "فرappé",
    items: [
      { en: "Frappé Vanilla", ar: "فرappé فانيليا", price: 180, cold: true },
      { en: "Salted Caramel Frappé", ar: "فرappé كaramel", price: 185, cold: true },
      { en: "Chocolate Frappé", ar: "فرappé شوكولاتة", price: 190, cold: true },
      { en: "Pistachio Frappé", ar: "فرappé فستق", price: 220, cold: true },
      { en: "Almond Frappé", ar: "فرappé لوز", price: 210, cold: true },
      { en: "Raspberry Frappé", ar: "فرappé توت", price: 190, cold: true },
    ],
  },
  {
    en: "Smoothie",
    ar: "سموذي",
    items: [
      { en: "Mango Smoothie", ar: "مانجو", price: 165, cold: true },
      { en: "Smoothie Mix Berry", ar: "توت مشكل", price: 155, cold: true },
      { en: "Green Apple Smoothie", ar: "تفاح أخضر", price: 153, cold: true },
      { en: "Smoothie Piña Colada", ar: "piña colada", price: 160, cold: true },
      { en: "Lemon Mint Smoothie", ar: "ليمون نعناع", price: 135, cold: true },
      { en: "Smoothie Very Passion", ar: "passion fruit", price: 150, cold: true },
      { en: "Strawberry Smoothie", ar: "فراولة", price: 150, cold: true },
      { en: "Watermelon Mint Smoothie", ar: "بطيخ نعناع", price: 130, cold: true },
      { en: "Kiwi Lemon Smoothie", ar: "كiwi ليمون", price: 175, cold: true },
      { en: "Red Grape Smoothie", ar: "عنب", price: 140, cold: true },
      { en: "Falconry Corn Smoothie", ar: "corn smoothie", price: 170, cold: true },
    ],
  },
  {
    en: "Cocktails",
    ar: "كوكتيلات فواكه",
    items: [
      { en: "Banana Peanut Butter", ar: "موز وفول سوداني", price: 185, cold: true },
      { en: "Detox", ar: "detox", price: 140, cold: true },
      { en: "Energy", ar: "energy", price: 185, cold: true },
      { en: "Mon Day", ar: "mon day", price: 250, cold: true },
      { en: "Glowing", ar: "glowing", price: 140, cold: true },
      { en: "Chocolate Refresh", ar: "شوكولاتة", price: 189, cold: true },
      { en: "Kiwi Apple", ar: "كiwi وتفاح", price: 200, cold: true },
      { en: "Greek Yogurt Cocktail", ar: "زبادي يوناني", price: 265, cold: true },
      { en: "Avocado Nuts Honey", ar: "أفocado", price: 250, cold: true },
      { en: "Avocado Power", ar: "avocado power", price: 240, cold: true },
      { en: "Kiwi Mango", ar: "كiwi مانجو", price: 230, cold: true },
      { en: "Guava Mint", ar: "جوافة نعناع", price: 145, cold: true },
      { en: "Passion Fruit Mango", ar: "passion مانجو", price: 175, cold: true },
    ],
  },
  {
    en: "Juices",
    ar: "عصائر طازجة",
    items: [
      { en: "Mango Juice", ar: "مانجو", price: 135, cold: true },
      { en: "Orange Juice", ar: "برتقال", price: 130, cold: true },
      { en: "Strawberry Juice", ar: "فراولة", price: 135, cold: true },
      { en: "Guava Juice", ar: "جوافة", price: 130, cold: true },
      { en: "Kiwi Juice", ar: "كiwi", price: 165, cold: true },
      { en: "Watermelon Juice", ar: "بطيخ", price: 150, cold: true },
      { en: "Cantaloupe Juice", ar: "شمام", price: 130, cold: true },
      { en: "Lemon Mint Juice", ar: "ليمون نعناع", price: 130, cold: true },
      { en: "Banana Juice", ar: "موز", price: 125, cold: true },
      { en: "Orange and Carrot Juice", ar: "برتقال وجزر", price: 149, cold: true },
      { en: "Pineapple Orange Juice", ar: "أnanas وبرتقال", price: 160, cold: true },
      { en: "Pineapple Juice", ar: "أnanas", price: 150, cold: true },
      { en: "Guava Mint Juice", ar: "جوافة نعناع", price: 145, cold: true },
    ],
  },
  {
    en: "Desserts & Sweets",
    ar: "حلويات",
    items: [
      { en: "Pistachio Tiramisu", ar: "tiramisu فستق", price: 240, vegetarian: true },
      { en: "Berries Cheesecake", ar: "cheesecake توت", price: 225, vegetarian: true },
      { en: "Banana Pudding", ar: "budding موز", price: 220, vegetarian: true },
      { en: "Tres Leches Pistachio", ar: "tres leches", price: 225, vegetarian: true },
      { en: "Lazy Cat Cake", ar: "lazy cat", price: 215, vegetarian: true },
      { en: "Molten Cake", ar: "molten cake", price: 220, vegetarian: true },
      { en: "Brownies Cake", ar: "براونيز", price: 220, vegetarian: true },
      { en: "San Sebastian Cheesecake", ar: "san sebastian", price: 220, vegetarian: true },
      { en: "Termessio", ar: "termessio", price: 220, vegetarian: true },
      { en: "Chocolate Rocher", ar: "rocher", price: 220, vegetarian: true },
      { en: "Creamy Bubel", ar: "bubel", price: 220, vegetarian: true },
      { en: "Fruit Salad", ar: "سلطة فواكه", price: 195, vegetarian: true },
      { en: "Watermelon Platter", ar: "طبق بطيخ", price: 210, vegetarian: true },
      { en: "Small Fruit Plate", ar: "طبق فواكه صغير", price: 299, vegetarian: true },
      { en: "Large Fruit Plate", ar: "طبق فواكه كبير", price: 430, vegetarian: true },
      { en: "Soul Stray Fire Chocolate Dessert", ar: "شوكولاتة soul", price: 330, vegetarian: true },
      { en: "Ice Cream", ar: "آيس كريم", price: 65, cold: true, vegetarian: true },
      { en: "Mixed Ice Cream", ar: "آيس كريم مشكل", price: 140, cold: true, vegetarian: true },
      { en: "Soul Mixed Ice Cream", ar: "آيس كريم soul", price: 170, cold: true, vegetarian: true },
      { en: "Mixed Nut Plate", ar: "طبق مكسرات", price: 200, vegetarian: true },
    ],
  },
  {
    en: "Hot Beverages",
    ar: "مشروبات ساخنة",
    items: [
      { en: "Cortado", ar: "cortado", price: 115, hot: true },
      { en: "Macchiato", ar: "macchiato", price: 110, hot: true },
      { en: "American Coffee", ar: "قهوة أمريكية", price: 110, hot: true },
      { en: "Latte", ar: "latte", price: 125, hot: true },
      { en: "Peanut Butter Latte", ar: "latte فول سوداني", price: 135, hot: true },
      { en: "Tea", ar: "شاي", price: 65, hot: true },
      { en: "Tea Pot", ar: "إبريق شاي", price: 80, hot: true },
      { en: "Clove Tea", ar: "شاي قرنفل", price: 95, hot: true },
      { en: "Tea Karak", ar: "شاي كarak", price: 145, hot: true },
      { en: "Sahlab with Nuts", ar: "sahlab", price: 115, hot: true },
      { en: "Pistachio Sahlab", ar: "sahlab فستق", price: 150, hot: true },
      { en: "Turkish Coffee Double", ar: "قهوة تركي", price: 80, hot: true },
      { en: "French Coffee", ar: "قهوة فرنسية", price: 100, hot: true },
      { en: "Hazelnut Coffee", ar: "قهوة بندق", price: 105, hot: true },
      { en: "Green Tea Pot", ar: "شاي أخضر", price: 85, hot: true },
      { en: "Nescafe", ar: "nescafe", price: 110, hot: true },
      { en: "Soul Stray Fire Chocolate Hot", ar: "شوكولاتة soul", price: 145, hot: true },
      { en: "Hot Cider", ar: "cider", price: 90, hot: true },
      { en: "Flat White", ar: "flat white", price: 125, hot: true },
      { en: "Mint Tea", ar: "نعناع", price: 65, hot: true },
      { en: "Anise Tea", ar: "ينson", price: 65, hot: true },
      { en: "Green Tea", ar: "شاي أخضر", price: 75, hot: true },
      { en: "Herbal Cocktail", ar: "أعشاب", price: 120, hot: true },
      { en: "Hot Red", ar: "hot red", price: 110, hot: true },
      { en: "Cinnamon Mint", ar: "قرفة نعناع", price: 110, hot: true },
      { en: "Gold Magic", ar: "gold magic", price: 145, hot: true },
      { en: "Salted Caramel Latte", ar: "latte كaramel", price: 140, hot: true },
      { en: "Latte Soul", ar: "latte soul", price: 135, hot: true, best: true },
    ],
  },
  {
    en: "Soft Drinks & Water",
    ar: "مشروبات غازية",
    items: [
      { en: "Soft Drink", ar: "مشروب غازي", price: 65, cold: true },
      { en: "Red Bull", ar: "red bull", price: 120, cold: true },
      { en: "Berill", ar: "berill", price: 70, cold: true },
      { en: "Club Soda", ar: "club soda", price: 80, cold: true },
      { en: "Mineral Water", ar: "مياه معدنية", price: 35, cold: true },
      { en: "Soda Water", ar: "صودا", price: 80, cold: true },
    ],
  },
  {
    en: "Extras",
    ar: "إضافات",
    items: [
      { en: "Extra Espresso", ar: "إسpresso إضافي", price: 49 },
      { en: "Extra Flavour", ar: "نكهة إضافية", price: 49 },
      { en: "Extra Milk", ar: "حليب إضافي", price: 45 },
      { en: "Extra Packet Tea", ar: "شاي إضافي", price: 30 },
      { en: "Extra Pistachios", ar: "فستق إضافي", price: 60 },
      { en: "Extra Nutella", ar: "nutella", price: 60 },
      { en: "Extra Lotus", ar: "lotus", price: 60 },
      { en: "Extra Nuts", ar: "مكسرات", price: 85 },
      { en: "Extra Honey", ar: "عسل", price: 45 },
    ],
  },
];
